- hosts: kubernetes-cluster
  tasks:
    - name: Create a Nexus Service object
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nexus-service
            annotations:
                prometheus.io/scrape: 'true'
                prometheus.io/path:   /
                prometheus.io/port:   '8081'
          spec:
            selector:
              app: nexus-server
            type: NodePort
            ports:
              - port: 8081
                targetPort: 8081
                nodePort: 32000
 